"""empty message

Revision ID: bf259d03d5f7
Revises: b7664316fb21
Create Date: 2018-12-24 14:40:13.252155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf259d03d5f7'
down_revision = 'b7664316fb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    op.drop_column('post', 'price')
    # ### end Alembic commands ###
