"""empty message

Revision ID: e9a843cb0001
Revises: fbde06b2e149
Create Date: 2018-12-28 16:48:35.281753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a843cb0001'
down_revision = 'fbde06b2e149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('condition', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'condition')
    # ### end Alembic commands ###
